In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_stata("easySHARE/easySHARE_rel9-0-0.dta", convert_categoricals=False)

In [3]:
df.shape

(488400, 108)

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df.head()

,mergeid,hhid,coupleid,wave,wavepart,int_version,int_year,int_month,country,country_mod,language,female,dn002_mod,dn003_mod,dn004_mod,age,birth_country,citizenship,iv009_mod,q34_re,isced1997_r,eduyears_mod,mar_stat,hhsize,partnerinhh,int_partner,age_partner,gender_partner,mother_alive,father_alive,siblings_alive,ch001_,ch021_mod,ch007_hh,ch007_km,sp002_mod,sp003_1_mod,sp003_2_mod,sp003_3_mod,sp008_,sp009_1_mod,sp009_2_mod,sp009_3_mod,books_age10,maths_age10,language_age10,vaccinated,childhood_health,sphus,chronic_mod,casp,euro1,euro2,euro3,euro4,euro5,euro6,euro7,euro8,euro9,euro10,euro11,euro12,eurod,bfi10_extra_mod,bfi10_agree_mod,bfi10_consc_mod,bfi10_neuro_mod,bfi10_open_mod,hc002_mod,hc012_,hc029_,maxgrip,adlwa,adla,iadla,iadlza,mobilityind,lgmuscle,grossmotor,finemotor,recall_1,recall_2,orienti,numeracy_1,numeracy_2,bmi,bmi2,smoking,ever_smoked,br010_mod,br015_,ep005_,ep009_mod,ep011_mod,ep013_mod,ep026_mod,ep036_mod,co007_,thinc_m,income_pct_w1,income_pct_w2,income_pct_w4,income_pct_w5,income_pct_w6,income_pct_w7,income_pct_w8,income_pct_w9
0,AT-000327-01,AT-000327-A,AT-000327-01-02,1,12,0,2004,6,11,40,11,0,7,1952,1,51.900002,40,40,4,2,3,-15.0,1,2,1,1,48.900002,1,1,1,-9,4,2,1,1,5,-9,-9,-9,5,-9,-9,-9,-13,-13,-13,-13,-13,1,0,37,0,0,0,0,0,0,0,0,0,0,0,0,0,-13.0,-13.0,-13.0,-13.0,-13.0,3,5,5,45,0,0,0,0,0,0,0,0,5,4,4,4,-13,32.787994,4,5,5,4,2,2,2,2,40.0,2,1,2,28721.849609,6,-13,-13,-13,-13,-13,-13,-13.0
1,AT-000327-01,AT-000327-A,AT-000327-01-02,2,12,1,2007,3,11,40,11,0,7,1952,1,54.700001,40,40,5,-13,3,-3.0,1,2,1,1,51.700001,1,1,5,-9,4,2,1,1,5,-9,-9,-9,5,-9,-9,-9,-13,-13,-13,-13,-13,5,1,24,1,1,1,0,1,1,0,1,1,0,1,1,9,-13.0,-13.0,-13.0,-13.0,-13.0,20,1,5,37,0,0,0,1,2,3,1,0,7,7,4,5,-13,20.281233,2,5,5,1,4,1,-9,-9,-9.0,-9,-9,3,26432.822266,-13,6,-13,-13,-13,-13,-13,-13.0
2,AT-000327-02,AT-000327-A,AT-000327-01-02,1,12,0,2004,6,11,40,11,1,7,1955,1,48.900002,40,40,4,2,3,3.0,1,2,1,1,51.900002,0,5,5,1,4,2,1,1,5,-9,-9,-9,1,4,-15,-15,-13,-13,-13,-13,-13,1,0,38,0,0,0,0,0,0,0,0,0,0,0,1,1,-13.0,-13.0,-13.0,-13.0,-13.0,2,5,5,42,0,0,0,0,0,0,0,0,8,7,4,4,-13,31.161373,4,5,5,2,3,2,2,2,40.0,2,5,2,28721.849609,6,-13,-13,-13,-13,-13,-13,-13.0
3,AT-000327-02,AT-000327-A,AT-000327-01-02,2,12,1,2007,3,11,40,11,1,7,1955,1,51.700001,40,40,5,-13,3,3.0,1,2,1,1,54.700001,0,5,5,1,4,2,1,1,5,-9,-9,-9,1,10,4,-15,-13,-13,-13,-13,-13,2,1,30,1,0,0,0,0,0,0,1,0,0,0,1,3,-13.0,-13.0,-13.0,-13.0,-13.0,6,5,5,40,0,0,0,0,2,0,1,0,8,7,4,5,-13,30.461119,4,5,5,1,1,2,1,2,28.0,2,5,3,26432.822266,-13,6,-13,-13,-13,-13,-13,-13.0
4,AT-000674-01,AT-000674-A,,4,456,0,2011,11,11,40,11,1,3,1952,1,59.700001,40,40,4,-13,5,3.0,6,1,3,-9,-9.000000,-9,5,5,-9,2,1,5,5,5,-9,-9,-9,5,-9,-9,-9,-13,-13,-13,-13,-13,3,1,44,0,0,0,0,0,0,0,0,1,0,0,0,1,-13.0,-13.0,-13.0,-13.0,-13.0,2,5,5,-15,0,0,0,0,0,0,0,0,2,1,4,5,5,24.023809,2,5,5,5,1,2,3,-9,50.0,1,5,4,9167.821289,-13,-13,1,-13,-13,-13,-13,-13.0

In [6]:
pd.set_option('display.max_rows', 150)
df.dtypes

mergeid              object
hhid                 object
coupleid             object
wave                   int8
wavepart              int32
int_version            int8
int_year              int16
int_month              int8
country                int8
country_mod           int16
language               int8
female                 int8
dn002_mod              int8
dn003_mod             int16
dn004_mod              int8
age                 float32
birth_country         int16
citizenship           int16
iv009_mod              int8
q34_re                 int8
isced1997_r            int8
eduyears_mod        float32
mar_stat               int8
hhsize                 int8
partnerinhh            int8
int_partner            int8
age_partner         float32
gender_partner         int8
mother_alive           int8
father_alive           int8
siblings_alive         int8
ch001_                 int8
ch021_mod              int8
ch007_hh               int8
ch007_km               int8
sp002_mod              int8
sp003_1_mod            int8
sp003_2_mod            int8
sp003_3_mod            int8
sp008_                 int8
sp009_1_mod            int8
sp009_2_mod            int8
sp009_3_mod            int8
books_age10            int8
maths_age10            int8
language_age10         int8
vaccinated             int8
childhood_health       int8
sphus                  int8
chronic_mod            int8
casp                   int8
euro1                  int8
euro2                  int8
euro3                  int8
euro4                  int8
euro5                  int8
euro6                  int8
euro7                  int8
euro8                  int8
euro9                  int8
euro10                 int8
euro11                 int8
euro12                 int8
eurod                  int8
bfi10_extra_mod     float32
bfi10_agree_mod     float32
bfi10_consc_mod     float32
bfi10_neuro_mod     float32
bfi10_open_mod      float32
hc002_mod              int8
hc012_                 int8
hc029_                 int8
maxgrip                int8
adlwa                  int8
adla                   int8
iadla                  int8
iadlza                 int8
mobilityind            int8
lgmuscle               int8
grossmotor             int8
finemotor              int8
recall_1               int8
recall_2               int8
orienti                int8
numeracy_1             int8
numeracy_2             int8
bmi                 float32
bmi2                   int8
smoking                int8
ever_smoked            int8
br010_mod              int8
br015_                 int8
ep005_                 int8
ep009_mod              int8
ep011_mod              int8
ep013_mod           float64
ep026_mod              int8
ep036_mod              int8
co007_                 int8
thinc_m             float32
income_pct_w1          int8
income_pct_w2          int8
income_pct_w4          int8
income_pct_w5          int8
income_pct_w6          int8
income_pct_w7          int8
income_pct_w8          int8
income_pct_w9       float64
dtype: object

# Preprocessing

In [56]:
df_preprocessed = df.copy()

#remove variables that are not needed
df_preprocessed = df_preprocessed.drop(columns=["wavepart", "int_year", "int_month", "country", "language", "dn002_mod", "dn003_mod", "birth_country", "iv009_mod", "q34_re", "eduyears_mod","int_partner", "sp003_1_mod", "sp003_2_mod", "sp003_3_mod", "sp009_1_mod", "sp009_2_mod", "sp009_3_mod","casp", "euro1", "euro2", "euro3", "euro4", "euro5", "euro6", "euro7", "euro8", "euro9", "euro10", "euro11", "euro12", "bfi10_extra_mod", "bfi10_agree_mod", "bfi10_consc_mod", "bfi10_neuro_mod", "bfi10_open_mod", "ep009_mod", "ep011_mod", "ep013_mod", "ep026_mod", "ep036_mod", "adlwa", "iadla", "bmi2", "numeracy_1", "numeracy_2", "income_pct_w1", "income_pct_w2", "income_pct_w4", "income_pct_w5", "income_pct_w6", "income_pct_w7", "income_pct_w8", "income_pct_w9"])

#drop variables only in wave 3 and 5 and 7
df_preprocessed = df_preprocessed.drop(columns=["books_age10", "maths_age10", "language_age10", "vaccinated", "childhood_health"])

In [57]:
features = [c for c in df_preprocessed.columns if c not in ["mergeid", "hhid", "coupleid"]]

#missing values
(df_preprocessed[features] < 0).any(axis=0)

wave              False
int_version        True
country_mod       False
female            False
dn004_mod          True
age                True
citizenship        True
isced1997_r        True
mar_stat           True
hhsize            False
partnerinhh       False
age_partner        True
gender_partner     True
mother_alive       True
father_alive       True
siblings_alive     True
ch001_             True
ch021_mod          True
ch007_hh           True
ch007_km           True
sp002_mod          True
sp008_             True
sphus              True
chronic_mod        True
eurod              True
hc002_mod          True
hc012_             True
hc029_             True
maxgrip            True
adla               True
iadlza             True
mobilityind        True
lgmuscle           True
grossmotor         True
finemotor          True
recall_1           True
recall_2           True
orienti            True
bmi                True
smoking            True
ever_smoked        True
br010_mod          True
br015_             True
ep005_             True
co007_             True
thinc_m            True
dtype: bool

In [58]:
#missing values numbers
(df_preprocessed[features] < 0).sum(axis=0)

wave                   0
int_version        28454
country_mod            0
female                 0
dn004_mod          30297
age                   24
citizenship         3251
isced1997_r        32304
mar_stat           30592
hhsize                 0
partnerinhh            0
age_partner       138115
gender_partner    137987
mother_alive       45011
father_alive       48428
siblings_alive    126130
ch001_             94193
ch021_mod         132701
ch007_hh          153721
ch007_km          153642
sp002_mod          93852
sp008_            132883
sphus               1786
chronic_mod        30386
eurod             106490
hc002_mod          34652
hc012_             30567
hc029_             34556
maxgrip            46813
adla               30855
iadlza             30855
mobilityind        31233
lgmuscle           30452
grossmotor         31233
finemotor          31233
recall_1           43465
recall_2           43336
orienti           159657
bmi                44529
smoking           122221
ever_smoked        95400
br010_mod         298309
br015_             93730
ep005_             34503
co007_             39298
thinc_m            94139
dtype: int64

In [59]:
# remove wave 3 and 7 since SHARELIFE interviews and questions are different
df_preprocessed = df_preprocessed[~df_preprocessed["wave"].isin([3, 7])]

In [60]:
#remove dependent variable missing values
df_preprocessed = df_preprocessed[~df_preprocessed["eurod"] < 0]

In [61]:
#missing values numbers
(df_preprocessed[features] < 0).sum(axis=0)

wave                   0
int_version            0
country_mod            0
female                 0
dn004_mod           1447
age                   13
citizenship         1724
isced1997_r         3070
mar_stat            1472
hhsize                 0
partnerinhh            0
age_partner       103029
gender_partner    102935
mother_alive       15307
father_alive       18283
siblings_alive     84778
ch001_              1589
ch021_mod          37071
ch007_hh           54009
ch007_km           53932
sp002_mod            499
sp008_             37282
sphus                173
chronic_mod          255
eurod                  0
hc002_mod           2955
hc012_               131
hc029_              2629
maxgrip            25986
adla                 118
iadlza               118
mobilityind          176
lgmuscle              83
grossmotor           176
finemotor            176
recall_1            3661
recall_2            3693
orienti            61836
bmi                10196
smoking            24485
ever_smoked         2600
br010_mod         183704
br015_               688
ep005_              2735
co007_              6992
thinc_m             2341
dtype: int64

In [62]:
df_preprocessed["country_mod"]

0          40
1          40
2          40
3          40
4          40
         ...
488391    703
488393    703
488394    703
488396    703
488397    703
Name: country_mod, Length: 368471, dtype: int16

In [63]:
ISO_to_country_abbrev = {
    40: "AT",
    56: "BE",
    100: "BG",
    191: "HR",
    196: "CY",
    203: "CZ",
    208: "DK",
    233: "EE",
    246: "FI",
    250: "FR",
    276: "DE",
    300: "GR",
    348: "HU",
    372: "IE",
    376: "IL",
    380: "IT",
    428: "LV",
    440: "LT",
    442: "LU",
    470: "MT",
    528: "NL",
    616: "PL",
    620: "PT",
    642: "RO",
    703: "SK",
    705: "SI",
    724: "ES",
    752: "SE",
    756: "CH",
}

df_preprocessed["country"] = df_preprocessed["country_mod"].replace(ISO_to_country_abbrev)
df_preprocessed["country"].unique()

cols_to_drop = ["country_mod", "wave"]
df_preprocessed = df_preprocessed.drop(columns=cols_to_drop)

In [64]:
dummy_needed = ["country"]

In [65]:
def add_NA(df, col):
    df.loc[df[col] < 0, col] = -1
    return df

In [66]:
na_one_five_mapping = {
    -1: "NA",
    1: "yes",
    5: "no",
}

In [67]:
def preprocess_one_five_NA(df, cols):
    for col in cols:
        df = add_NA(df, col)
        df[col] = df[col].replace(na_one_five_mapping)

    return df

In [68]:
def preprocess_cont_NA(df, cols):
    for col in cols:
        df = add_NA(df, col)
        df[col + "_NA"] = (df[col] == -1).astype(int)
        df[col] = df[col].replace(-1, 0)
    
    return df

In [69]:
def preprocess_cat_NA(df, cols, mapping):
    for col in cols:
        df = add_NA(df, col)
        df[col] = df[col].replace(mapping[col])

    return df

In [70]:
to_rename = {
    "dn004_mod": "born_in_itw_country",
    "isced1997_r": "education",
    "mar_stat": "marital_status",
    "ch007_hh": "one_or_more_child_in_hh",
    "ch007_km": "child_within_km",
    "sp002_mod": "help_outside_hh",
    "sp008_": "given_help",
    "eurod": "depression_scale",
    "hc012_": "hospitalised_last_year",
    "hc029_": "nursing_home_last_year",
    "br010_mod": "drinking_behaviour",
    "br015_": "vigorous_activity",
    "ep005_": "job_situation",
    "co007_": "househol_ends_meet",
}

to_rename_before_preprocess = {
    "ch001_": "nb_children",
    "ch021_mod": "nb_grandchildren",
    "hc002_mod": "nb_doctor_visits",
    "adla": "daily_activities_index",
    "iadlza": "instrumental_activities_index",
    "thinc_m": "hh_net_income",
}

In [71]:
cols_one_five_NA = [
    "dn004_mod",
    "citizenship",
    "mother_alive",
    "father_alive",
    "ch007_hh",
    "ch007_km",
    "sp002_mod",
    "sp008_",
    "hc012_",
    "smoking",
    "ever_smoked",
]

In [72]:
cols_cont_NA = [
    "age",
    "age_partner",
    "siblings_alive",
    "nb_children",
    "nb_grandchildren",
    "chronic_mod",
    "nb_doctor_visits",
    "maxgrip",
    "daily_activities_index",
    "instrumental_activities_index",
    "mobilityind",
    "lgmuscle",
    "grossmotor",
    "finemotor",
    "recall_1",
    "recall_2",
    "orienti",
    "bmi",
    "hh_net_income",
]

In [73]:
cols_cat_NA = [
    "isced1997_r",
    "mar_stat",
    "partnerinhh",
    "gender_partner",
    "sphus",
    "hc029_",
    "br010_mod",
    "br015_",
    "co007_",
]

cat_mapping = {
    "isced1997_r": {
        -1: "NA",
        0: "none",
        1: "level_1",
        2: "level_2",
        3: "level_3",
        4: "level_4",
        5: "level_5",
        6: "level_6",
        95: "studying",
        96: "other",
    },
    "mar_stat": {
        -1: "NA",
        0: "none",
        1: "married",
        2: "reg_partnership",
        3: "separated",
        4: "single",
        5: "divorced",
        6: "widowed",
    },
    "partnerinhh": {
        -1: "NA",
        1: "yes",
        3: "no",
        97: "other",
    },
    "gender_partner": {
        -1: "NA",
        0: "male",
        1: "female"
    },
    "sphus": {
        -1: "NA",
        1: "excellent",
        2: "very_good",
        3: "good",
        4: "fair",
        5: "poor",
    },
    "hc029_": {
        -1: "NA",
        1: "yes_temporarily",
        3: "yes_permanently",
        5: "no",
    },
    "br010_mod": {
        -1: "NA",
        1: "not_at_all",
        2: "less_than_once_a_month",
        3: "once_twice_a_month",
        4: "once_twice_a_week",
        5: "three_four_times_a_week",
        6: "five_six_times_a_week",
        7: "every_day",
    },
    "br015_": {
        -1: "NA",
        1: "more_than_once_a_week",
        2: "once_a_week",
        3: "once_three_times_a_month",
        2: "never",
    },
    "co007_": {
        -1: "NA",
        1: "with_great_difficulty",
        2: "with_some_difficulty",
        3: "fairly_easily",
        4: "easily",
    },
}

In [74]:
df_prepro = df_preprocessed.copy()

df_prepro = df_prepro.rename(columns=to_rename_before_preprocess)
df_prepro = preprocess_one_five_NA(df_prepro, cols_one_five_NA)
df_prepro = preprocess_cont_NA(df_prepro, cols_cont_NA)
df_prepro = preprocess_cat_NA(df_prepro, cols_cat_NA, cat_mapping)
df_prepro = df_prepro.rename(columns=to_rename)
df_prepro.head()

,mergeid,hhid,coupleid,int_version,female,born_in_itw_country,age,citizenship,education,marital_status,hhsize,partnerinhh,age_partner,gender_partner,mother_alive,father_alive,siblings_alive,nb_children,nb_grandchildren,one_or_more_child_in_hh,child_within_km,help_outside_hh,given_help,sphus,chronic_mod,depression_scale,nb_doctor_visits,hospitalised_last_year,nursing_home_last_year,maxgrip,daily_activities_index,instrumental_activities_index,mobilityind,lgmuscle,grossmotor,finemotor,recall_1,recall_2,orienti,bmi,smoking,ever_smoked,drinking_behaviour,vigorous_activity,job_situation,househol_ends_meet,hh_net_income,country,age_NA,age_partner_NA,siblings_alive_NA,nb_children_NA,nb_grandchildren_NA,chronic_mod_NA,nb_doctor_visits_NA,maxgrip_NA,daily_activities_index_NA,instrumental_activities_index_NA,mobilityind_NA,lgmuscle_NA,grossmotor_NA,finemotor_NA,recall_1_NA,recall_2_NA,orienti_NA,bmi_NA,hh_net_income_NA
0,AT-000327-01,AT-000327-A,AT-000327-01-02,0,0,yes,51.900002,40,level_3,married,2,yes,48.900002,female,yes,yes,0,4,2,yes,yes,no,no,excellent,0,0,3,no,no,45,0,0,0,0,0,0,5,4,4,32.787994,no,no,once_twice_a_week,never,2,with_some_difficulty,28721.849609,AT,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,AT-000327-01,AT-000327-A,AT-000327-01-02,1,0,yes,54.700001,40,level_3,married,2,yes,51.700001,female,yes,no,0,4,2,yes,yes,no,no,poor,1,9,20,yes,no,37,0,1,2,3,1,0,7,7,4,20.281233,no,no,not_at_all,4,1,fairly_easily,26432.822266,AT,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,AT-000327-02,AT-000327-A,AT-000327-01-02,0,1,yes,48.900002,40,level_3,married,2,yes,51.900002,male,no,no,1,4,2,yes,yes,no,yes,excellent,0,1,2,no,no,42,0,0,0,0,0,0,8,7,4,31.161373,no,no,less_than_once_a_month,once_three_times_a_month,2,with_some_difficulty,28721.849609,AT,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,AT-000327-02,AT-000327-A,AT-000327-01-02,1,1,yes,51.700001,40,level_3,married,2,yes,54.700001,male,no,no,1,4,2,yes,yes,no,yes,very_good,1,3,6,no,no,40,0,0,2,0,1,0,8,7,4,30.461119,no,no,not_at_all,more_than_once_a_week,2,fairly_easily,26432.822266,AT,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,AT-000674-01,AT-000674-A,,0,1,yes,59.700001,40,level_5,widowed,1,no,0.000000,NA,no,no,0,2,1,no,no,no,no,good,1,1,2,no,no,0,0,0,0,0,0,0,2,1,4,24.023809,no,no,three_four_times_a_week,more_than_once_a_week,2,easily,9167.821289,AT,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

In [77]:
# get dummies

cols_to_get_dummies = [col for col in df_prepro.columns if "NA" not in col and col not in cols_cont_NA and col not in ["mergeid", "hhid", "coupleid", "int_version", "female", "hhsize", "depression_scale"] and col not in dummy_needed]

In [78]:
cols_to_get_dummies

['born_in_itw_country',
 'citizenship',
 'education',
 'marital_status',
 'partnerinhh',
 'gender_partner',
 'mother_alive',
 'father_alive',
 'one_or_more_child_in_hh',
 'child_within_km',
 'help_outside_hh',
 'given_help',
 'sphus',
 'hospitalised_last_year',
 'nursing_home_last_year',
 'smoking',
 'ever_smoked',
 'drinking_behaviour',
 'vigorous_activity',
 'job_situation',
 'househol_ends_meet']