In [1]:
import pandas as pd

In [2]:
df = pd.read_stata("../data/easySHARE/easySHARE_rel9-0-0.dta", convert_categoricals=False)

In [3]:
df.shape

(488400, 108)

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df.head()

,mergeid,hhid,coupleid,wave,wavepart,int_version,int_year,int_month,country,country_mod,language,female,dn002_mod,dn003_mod,dn004_mod,age,birth_country,citizenship,iv009_mod,q34_re,isced1997_r,eduyears_mod,mar_stat,hhsize,partnerinhh,int_partner,age_partner,gender_partner,mother_alive,father_alive,siblings_alive,ch001_,ch021_mod,ch007_hh,ch007_km,sp002_mod,sp003_1_mod,sp003_2_mod,sp003_3_mod,sp008_,sp009_1_mod,sp009_2_mod,sp009_3_mod,books_age10,maths_age10,language_age10,vaccinated,childhood_health,sphus,chronic_mod,casp,euro1,euro2,euro3,euro4,euro5,euro6,euro7,euro8,euro9,euro10,euro11,euro12,eurod,bfi10_extra_mod,bfi10_agree_mod,bfi10_consc_mod,bfi10_neuro_mod,bfi10_open_mod,hc002_mod,hc012_,hc029_,maxgrip,adlwa,adla,iadla,iadlza,mobilityind,lgmuscle,grossmotor,finemotor,recall_1,recall_2,orienti,numeracy_1,numeracy_2,bmi,bmi2,smoking,ever_smoked,br010_mod,br015_,ep005_,ep009_mod,ep011_mod,ep013_mod,ep026_mod,ep036_mod,co007_,thinc_m,income_pct_w1,income_pct_w2,income_pct_w4,income_pct_w5,income_pct_w6,income_pct_w7,income_pct_w8,income_pct_w9
0,AT-000327-01,AT-000327-A,AT-000327-01-02,1,12,0,2004,6,11,40,11,0,7,1952,1,51.900002,40,40,4,2,3,-15.0,1,2,1,1,48.900002,1,1,1,-9,4,2,1,1,5,-9,-9,-9,5,-9,-9,-9,-13,-13,-13,-13,-13,1,0,37,0,0,0,0,0,0,0,0,0,0,0,0,0,-13.0,-13.0,-13.0,-13.0,-13.0,3,5,5,45,0,0,0,0,0,0,0,0,5,4,4,4,-13,32.787994,4,5,5,4,2,2,2,2,40.0,2,1,2,28721.849609,6,-13,-13,-13,-13,-13,-13,-13.0
1,AT-000327-01,AT-000327-A,AT-000327-01-02,2,12,1,2007,3,11,40,11,0,7,1952,1,54.700001,40,40,5,-13,3,-3.0,1,2,1,1,51.700001,1,1,5,-9,4,2,1,1,5,-9,-9,-9,5,-9,-9,-9,-13,-13,-13,-13,-13,5,1,24,1,1,1,0,1,1,0,1,1,0,1,1,9,-13.0,-13.0,-13.0,-13.0,-13.0,20,1,5,37,0,0,0,1,2,3,1,0,7,7,4,5,-13,20.281233,2,5,5,1,4,1,-9,-9,-9.0,-9,-9,3,26432.822266,-13,6,-13,-13,-13,-13,-13,-13.0
2,AT-000327-02,AT-000327-A,AT-000327-01-02,1,12,0,2004,6,11,40,11,1,7,1955,1,48.900002,40,40,4,2,3,3.0,1,2,1,1,51.900002,0,5,5,1,4,2,1,1,5,-9,-9,-9,1,4,-15,-15,-13,-13,-13,-13,-13,1,0,38,0,0,0,0,0,0,0,0,0,0,0,1,1,-13.0,-13.0,-13.0,-13.0,-13.0,2,5,5,42,0,0,0,0,0,0,0,0,8,7,4,4,-13,31.161373,4,5,5,2,3,2,2,2,40.0,2,5,2,28721.849609,6,-13,-13,-13,-13,-13,-13,-13.0
3,AT-000327-02,AT-000327-A,AT-000327-01-02,2,12,1,2007,3,11,40,11,1,7,1955,1,51.700001,40,40,5,-13,3,3.0,1,2,1,1,54.700001,0,5,5,1,4,2,1,1,5,-9,-9,-9,1,10,4,-15,-13,-13,-13,-13,-13,2,1,30,1,0,0,0,0,0,0,1,0,0,0,1,3,-13.0,-13.0,-13.0,-13.0,-13.0,6,5,5,40,0,0,0,0,2,0,1,0,8,7,4,5,-13,30.461119,4,5,5,1,1,2,1,2,28.0,2,5,3,26432.822266,-13,6,-13,-13,-13,-13,-13,-13.0
4,AT-000674-01,AT-000674-A,,4,456,0,2011,11,11,40,11,1,3,1952,1,59.700001,40,40,4,-13,5,3.0,6,1,3,-9,-9.000000,-9,5,5,-9,2,1,5,5,5,-9,-9,-9,5,-9,-9,-9,-13,-13,-13,-13,-13,3,1,44,0,0,0,0,0,0,0,0,1,0,0,0,1,-13.0,-13.0,-13.0,-13.0,-13.0,2,5,5,-15,0,0,0,0,0,0,0,0,2,1,4,5,5,24.023809,2,5,5,5,1,2,3,-9,50.0,1,5,4,9167.821289,-13,-13,1,-13,-13,-13,-13,-13.0

In [6]:
pd.set_option('display.max_rows', 150)
df.dtypes

mergeid              object
hhid                 object
coupleid             object
wave                   int8
wavepart              int32
int_version            int8
int_year              int16
int_month              int8
country                int8
country_mod           int16
language               int8
female                 int8
dn002_mod              int8
dn003_mod             int16
dn004_mod              int8
age                 float32
birth_country         int16
citizenship           int16
iv009_mod              int8
q34_re                 int8
isced1997_r            int8
eduyears_mod        float32
mar_stat               int8
hhsize                 int8
partnerinhh            int8
int_partner            int8
age_partner         float32
gender_partner         int8
mother_alive           int8
father_alive           int8
siblings_alive         int8
ch001_                 int8
ch021_mod              int8
ch007_hh               int8
ch007_km               int8
sp002_mod              int8
sp003_1_mod            int8
sp003_2_mod            int8
sp003_3_mod            int8
sp008_                 int8
sp009_1_mod            int8
sp009_2_mod            int8
sp009_3_mod            int8
books_age10            int8
maths_age10            int8
language_age10         int8
vaccinated             int8
childhood_health       int8
sphus                  int8
chronic_mod            int8
casp                   int8
euro1                  int8
euro2                  int8
euro3                  int8
euro4                  int8
euro5                  int8
euro6                  int8
euro7                  int8
euro8                  int8
euro9                  int8
euro10                 int8
euro11                 int8
euro12                 int8
eurod                  int8
bfi10_extra_mod     float32
bfi10_agree_mod     float32
bfi10_consc_mod     float32
bfi10_neuro_mod     float32
bfi10_open_mod      float32
hc002_mod              int8
hc012_                 int8
hc029_                 int8
maxgrip                int8
adlwa                  int8
adla                   int8
iadla                  int8
iadlza                 int8
mobilityind            int8
lgmuscle               int8
grossmotor             int8
finemotor              int8
recall_1               int8
recall_2               int8
orienti                int8
numeracy_1             int8
numeracy_2             int8
bmi                 float32
bmi2                   int8
smoking                int8
ever_smoked            int8
br010_mod              int8
br015_                 int8
ep005_                 int8
ep009_mod              int8
ep011_mod              int8
ep013_mod           float64
ep026_mod              int8
ep036_mod              int8
co007_                 int8
thinc_m             float32
income_pct_w1          int8
income_pct_w2          int8
income_pct_w4          int8
income_pct_w5          int8
income_pct_w6          int8
income_pct_w7          int8
income_pct_w8          int8
income_pct_w9       float64
dtype: object

In [7]:
features = [c for c in df.columns if c not in ["mergeid", "hhid", "coupleid"]]

#missing values
(df[features] < 0).sum(axis=0)

wave                     0
wavepart                 0
int_version          28454
int_year                 0
int_month                0
country                  0
country_mod              0
language                 0
female                   0
dn002_mod              194
dn003_mod               24
dn004_mod            30297
age                     24
birth_country         3779
citizenship           3251
iv009_mod            51481
q34_re              469796
isced1997_r          32304
eduyears_mod         46263
mar_stat             30592
hhsize                   0
partnerinhh              0
int_partner         137987
age_partner         138115
gender_partner      137987
mother_alive         45011
father_alive         48428
siblings_alive      126130
ch001_               94193
ch021_mod           132701
ch007_hh            153721
ch007_km            153642
sp002_mod            93852
sp003_1_mod         406208
sp003_2_mod         455102
sp003_3_mod         476741
sp008_              132883
sp009_1_mod         391765
sp009_2_mod         458343
sp009_3_mod         479382
books_age10         334007
maths_age10         335552
language_age10      335906
vaccinated          349043
childhood_health    347296
sphus                 1786
chronic_mod          30386
casp                 70253
euro1               101212
euro2               102131
euro3               101996
euro4               102128
euro5               100834
euro6               101409
euro7               101305
euro8               100487
euro9               101277
euro10              102045
euro11              101695
euro12              101263
eurod               106490
bfi10_extra_mod     351315
bfi10_agree_mod     351139
bfi10_consc_mod     351134
bfi10_neuro_mod     351066
bfi10_open_mod      351489
hc002_mod            34652
hc012_               30567
hc029_               34556
maxgrip              46813
adlwa                30855
adla                 30855
iadla                30855
iadlza               30855
mobilityind          31233
lgmuscle             30452
grossmotor           31233
finemotor            31233
recall_1             43465
recall_2             43336
orienti             159657
numeracy_1          317332
numeracy_2          164087
bmi                  44529
bmi2                 44529
smoking             122221
ever_smoked          95400
br010_mod           298309
br015_               93730
ep005_               34503
ep009_mod           390705
ep011_mod           451768
ep013_mod           390584
ep026_mod           422234
ep036_mod           391554
co007_               39298
thinc_m              94139
income_pct_w1       457984
income_pct_w2       452303
income_pct_w4       430418
income_pct_w5       422362
income_pct_w6       420345
income_pct_w7       474452
income_pct_w8       434705
income_pct_w9       418953
dtype: int64

# Preprocessing

In [8]:
df_preprocessed = df.copy()

#remove variables that are not needed
df_preprocessed = df_preprocessed.drop(columns=["wavepart", "int_year", "int_month", "country", "language", "dn002_mod", "dn003_mod", "birth_country", "iv009_mod", "q34_re", "eduyears_mod","int_partner", "sp003_1_mod", "sp003_2_mod", "sp003_3_mod", "sp009_1_mod", "sp009_2_mod", "sp009_3_mod","casp", "euro1", "euro2", "euro3", "euro4", "euro5", "euro6", "euro7", "euro8", "euro9", "euro10", "euro11", "euro12", "bfi10_extra_mod", "bfi10_agree_mod", "bfi10_consc_mod", "bfi10_neuro_mod", "bfi10_open_mod", "ep009_mod", "ep011_mod", "ep013_mod", "ep026_mod", "ep036_mod", "adlwa", "iadla", "bmi2", "numeracy_1", "numeracy_2", "income_pct_w1", "income_pct_w2", "income_pct_w4", "income_pct_w5", "income_pct_w6", "income_pct_w7", "income_pct_w8", "income_pct_w9"])

#drop variables only in wave 3 and 5 and 7
df_preprocessed = df_preprocessed.drop(columns=["books_age10", "maths_age10", "language_age10", "vaccinated", "childhood_health"])

In [9]:
features = [c for c in df_preprocessed.columns if c not in ["mergeid", "hhid", "coupleid"]]

#missing values
(df_preprocessed[features] < 0).any(axis=0)

wave              False
int_version        True
country_mod       False
female            False
dn004_mod          True
age                True
citizenship        True
isced1997_r        True
mar_stat           True
hhsize            False
partnerinhh       False
age_partner        True
gender_partner     True
mother_alive       True
father_alive       True
siblings_alive     True
ch001_             True
ch021_mod          True
ch007_hh           True
ch007_km           True
sp002_mod          True
sp008_             True
sphus              True
chronic_mod        True
eurod              True
hc002_mod          True
hc012_             True
hc029_             True
maxgrip            True
adla               True
iadlza             True
mobilityind        True
lgmuscle           True
grossmotor         True
finemotor          True
recall_1           True
recall_2           True
orienti            True
bmi                True
smoking            True
ever_smoked        True
br010_mod          True
br015_             True
ep005_             True
co007_             True
thinc_m            True
dtype: bool

In [10]:
#missing values numbers
(df_preprocessed[features] < 0).sum(axis=0)

wave                   0
int_version        28454
country_mod            0
female                 0
dn004_mod          30297
age                   24
citizenship         3251
isced1997_r        32304
mar_stat           30592
hhsize                 0
partnerinhh            0
age_partner       138115
gender_partner    137987
mother_alive       45011
father_alive       48428
siblings_alive    126130
ch001_             94193
ch021_mod         132701
ch007_hh          153721
ch007_km          153642
sp002_mod          93852
sp008_            132883
sphus               1786
chronic_mod        30386
eurod             106490
hc002_mod          34652
hc012_             30567
hc029_             34556
maxgrip            46813
adla               30855
iadlza             30855
mobilityind        31233
lgmuscle           30452
grossmotor         31233
finemotor          31233
recall_1           43465
recall_2           43336
orienti           159657
bmi                44529
smoking           122221
ever_smoked        95400
br010_mod         298309
br015_             93730
ep005_             34503
co007_             39298
thinc_m            94139
dtype: int64

In [11]:
# remove wave 3 and 7 since SHARELIFE interviews and questions are different
df_preprocessed = df_preprocessed[~df_preprocessed["wave"].isin([3, 7])]

In [12]:
#remove dependent variable missing values
df_preprocessed = df_preprocessed[~df_preprocessed["eurod"] < 0]

In [13]:
#missing values numbers
(df_preprocessed[features] < 0).sum(axis=0)

wave                   0
int_version            0
country_mod            0
female                 0
dn004_mod           1447
age                   13
citizenship         1724
isced1997_r         3070
mar_stat            1472
hhsize                 0
partnerinhh            0
age_partner       103029
gender_partner    102935
mother_alive       15307
father_alive       18283
siblings_alive     84778
ch001_              1589
ch021_mod          37071
ch007_hh           54009
ch007_km           53932
sp002_mod            499
sp008_             37282
sphus                173
chronic_mod          255
eurod                  0
hc002_mod           2955
hc012_               131
hc029_              2629
maxgrip            25986
adla                 118
iadlza               118
mobilityind          176
lgmuscle              83
grossmotor           176
finemotor            176
recall_1            3661
recall_2            3693
orienti            61836
bmi                10196
smoking            24485
ever_smoked         2600
br010_mod         183704
br015_               688
ep005_              2735
co007_              6992
thinc_m             2341
dtype: int64

In [14]:
df_preprocessed["has_citizenship"] = (df_preprocessed["citizenship"] == df_preprocessed["country_mod"]).astype(int)
df_preprocessed.loc[df_preprocessed["citizenship"] < 0, "has_citizenship"] = -1
df_preprocessed.loc[df_preprocessed["has_citizenship"] == 0, "has_citizenship"] = 5

In [15]:
df_preprocessed["has_citizenship"].value_counts()

has_citizenship
 1    354856
 5     11891
-1      1724
Name: count, dtype: int64

In [16]:
df_preprocessed["country_mod"]

0          40
1          40
2          40
3          40
4          40
         ...
488391    703
488393    703
488394    703
488396    703
488397    703
Name: country_mod, Length: 368471, dtype: int16

In [17]:
ISO_to_country_abbrev = {
    40: "AT",
    56: "BE",
    100: "BG",
    191: "HR",
    196: "CY",
    203: "CZ",
    208: "DK",
    233: "EE",
    246: "FI",
    250: "FR",
    276: "DE",
    300: "GR",
    348: "HU",
    372: "IE",
    376: "IL",
    380: "IT",
    428: "LV",
    440: "LT",
    442: "LU",
    470: "MT",
    528: "NL",
    616: "PL",
    620: "PT",
    642: "RO",
    703: "SK",
    705: "SI",
    724: "ES",
    752: "SE",
    756: "CH",
}

df_preprocessed["country"] = df_preprocessed["country_mod"].replace(ISO_to_country_abbrev)
df_preprocessed["country"].unique()

array(['AT', 'BG', 'BE', 'CY', 'CZ', 'CH', 'DE', 'DK', 'EE', 'ES', 'FR',
       'FI', 'GR', 'HR', 'HU', 'IE', 'IT', 'IL', 'LT', 'LU', 'LV', 'MT',
       'NL', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK'], dtype=object)

In [18]:
dummy_needed = ["country"]

In [19]:
def add_NA(df, col):
    df.loc[df[col] < 0, col] = -1
    return df

In [20]:
na_one_five_mapping = {
    -1: "NA",
    1: "yes",
    5: "no",
}

In [21]:
def preprocess_one_five_NA(df, cols):
    for col in cols:
        df = add_NA(df, col)
        df[col] = df[col].replace(na_one_five_mapping)

    return df

In [22]:
def preprocess_cont_NA(df, cols):
    for col in cols:
        df = add_NA(df, col)
        df[col] = df[col].replace(-1, 0)
    
    return df

In [23]:
def preprocess_cat_NA(df, cols, mapping):
    for col in cols:
        df = add_NA(df, col)
        df[col] = df[col].replace(mapping[col])

    return df

In [24]:
to_rename = {
    "dn004_mod": "born_in_itw_country",
    "isced1997_r": "education",
    "mar_stat": "marital_status",
    "sp002_mod": "help_outside_hh",
    "sp008_": "given_help",
    "eurod": "depression_scale",
    "hc012_": "hospitalised_last_year",
    "hc029_": "nursing_home_last_year",
    "br015_": "vigorous_activity",
    "ep005_": "job_situation",
    "co007_": "household_ends_meet",
}

to_rename_before_preprocess = {
    "ch001_": "nb_children",
    "hc002_mod": "nb_doctor_visits",
    "adla": "daily_activities_index",
    "iadlza": "instrumental_activities_index",
    "thinc_m": "hh_net_income",
}

In [25]:
cols_one_five_NA = [
    "dn004_mod",
    "has_citizenship",
    "mother_alive",
    "father_alive",
    "sp002_mod",
    "hc012_",
    "smoking",
    "ever_smoked",
]

In [26]:
cols_cont_NA = [
    "age",
    "nb_children",
    "chronic_mod",
    "nb_doctor_visits",
    "maxgrip",
    "daily_activities_index",
    "instrumental_activities_index",
    "mobilityind",
    "lgmuscle",
    "grossmotor",
    "finemotor",
    "recall_1",
    "recall_2",
    "bmi",
    "hh_net_income",
]

In [27]:
cols_cat_NA = [
    "isced1997_r",
    "mar_stat",
    "partnerinhh",
    "sphus",
    "hc029_",
    "br015_",
    "co007_",
    "ep005_"
]

cat_mapping = {
    "isced1997_r": {
        -1: "NA",
        0: "none",
        1: "level_1",
        2: "level_2",
        3: "level_3",
        4: "level_4",
        5: "level_5",
        6: "level_6",
        95: "studying",
        96: "other",
    },
    "mar_stat": {
        -1: "NA",
        0: "none",
        1: "married",
        2: "reg_partnership",
        3: "separated",
        4: "single",
        5: "divorced",
        6: "widowed",
    },
    "partnerinhh": {
        -1: "NA",
        1: "yes",
        3: "no",
        97: "other",
    },
    "sphus": {
        -1: "NA",
        1: "excellent",
        2: "very_good",
        3: "good",
        4: "fair",
        5: "poor",
    },
    "hc029_": {
        -1: "NA",
        1: "yes_temporarily",
        3: "yes_permanently",
        5: "no",
    },
    "br015_": {
        -1: "NA",
        1: "more_than_once_a_week",
        2: "once_a_week",
        3: "once_three_times_a_month",
        2: "never",
    },
    "co007_": {
        -1: "NA",
        1: "with_great_difficulty",
        2: "with_some_difficulty",
        3: "fairly_easily",
        4: "easily",
    },
    "ep005_": {
        -1: "NA",
        1: "retired",
        2: "employed",
        3: "unemployed",
        4: "unable_to_work",
        5: "homemaker",
        97: "other",
    },
}

In [28]:
cols_to_drop = ["country_mod", "wave", "citizenship", "int_version"]
df_preprocessed = df_preprocessed.drop(columns=cols_to_drop)

In [29]:
def remove_columns(df, cols, threshold=0.1):
    col_to_remove = []
    for col in cols:
        if (df[col] < 0).sum() / df.shape[0] > threshold:
            col_to_remove.append(col)
    df = df.drop(columns=col_to_remove)
    print(f"Removed {len(col_to_remove)} columns with more than {threshold * 100}% missing values")
    return df, col_to_remove

In [30]:
def remove_rows(df, cols):
    num_rows_removed = 0
    for col in cols:
        num_rows_removed += df[df[col] < 0].shape[0]
        df = df[df[col] >= 0]
    print(f"Removed {num_rows_removed} rows with missing values")
    return df

In [31]:
features = [c for c in df_preprocessed.columns if c not in ["mergeid", "hhid", "coupleid", "country"]]

#missing values
df_preprocessed, cols_removed = remove_columns(df_preprocessed, features, threshold=0.1)

new_features = [c for c in df_preprocessed.columns if c not in ["mergeid", "hhid", "coupleid", "country"]]
df_preprocessed = remove_rows(df_preprocessed, new_features)

Removed 9 columns with more than 10.0% missing values
Removed 86496 rows with missing values

In [32]:
df_preprocessed.columns

Index(['mergeid', 'hhid', 'coupleid', 'female', 'dn004_mod', 'age',
       'isced1997_r', 'mar_stat', 'hhsize', 'partnerinhh', 'mother_alive',
       'father_alive', 'ch001_', 'sp002_mod', 'sphus', 'chronic_mod', 'eurod',
       'hc002_mod', 'hc012_', 'hc029_', 'maxgrip', 'adla', 'iadlza',
       'mobilityind', 'lgmuscle', 'grossmotor', 'finemotor', 'recall_1',
       'recall_2', 'bmi', 'smoking', 'ever_smoked', 'br015_', 'ep005_',
       'co007_', 'thinc_m', 'has_citizenship', 'country'],
      dtype='object')

In [33]:
df_prepro = df_preprocessed.copy()

df_prepro = df_prepro.rename(columns=to_rename_before_preprocess)
df_prepro = preprocess_one_five_NA(df_prepro, cols_one_five_NA)
df_prepro = preprocess_cont_NA(df_prepro, cols_cont_NA)
df_prepro = preprocess_cat_NA(df_prepro, cols_cat_NA, cat_mapping)
df_prepro = df_prepro.rename(columns=to_rename)
df_prepro.head()

,mergeid,hhid,coupleid,female,born_in_itw_country,age,education,marital_status,hhsize,partnerinhh,mother_alive,father_alive,nb_children,help_outside_hh,sphus,chronic_mod,depression_scale,nb_doctor_visits,hospitalised_last_year,nursing_home_last_year,maxgrip,daily_activities_index,instrumental_activities_index,mobilityind,lgmuscle,grossmotor,finemotor,recall_1,recall_2,bmi,smoking,ever_smoked,vigorous_activity,job_situation,household_ends_meet,hh_net_income,has_citizenship,country
0,AT-000327-01,AT-000327-A,AT-000327-01-02,0,yes,51.900002,level_3,married,2,yes,yes,yes,4,no,excellent,0,0,3,no,no,45,0,0,0,0,0,0,5,4,32.787994,no,no,never,employed,with_some_difficulty,28721.849609,yes,AT
1,AT-000327-01,AT-000327-A,AT-000327-01-02,0,yes,54.700001,level_3,married,2,yes,yes,no,4,no,poor,1,9,20,yes,no,37,0,1,2,3,1,0,7,7,20.281233,no,no,4,retired,fairly_easily,26432.822266,yes,AT
2,AT-000327-02,AT-000327-A,AT-000327-01-02,1,yes,48.900002,level_3,married,2,yes,no,no,4,no,excellent,0,1,2,no,no,42,0,0,0,0,0,0,8,7,31.161373,no,no,once_three_times_a_month,employed,with_some_difficulty,28721.849609,yes,AT
3,AT-000327-02,AT-000327-A,AT-000327-01-02,1,yes,51.700001,level_3,married,2,yes,no,no,4,no,very_good,1,3,6,no,no,40,0,0,2,0,1,0,8,7,30.461119,no,no,more_than_once_a_week,employed,fairly_easily,26432.822266,yes,AT
6,AT-000674-01,AT-000674-A,,1,yes,63.299999,level_5,widowed,1,no,yes,no,2,no,good,2,4,4,no,no,26,0,0,0,0,0,0,5,5,27.636055,no,no,once_three_times_a_month,retired,fairly_easily,15720.549805,yes,AT

In [34]:
# get dummies

cols_to_get_dummies = [col for col in df_prepro.columns if "NA" not in col and col not in cols_cont_NA and col not in ["mergeid", "hhid", "coupleid", "int_version", "female", "hhsize", "depression_scale"]]

In [35]:
df_prepro = pd.get_dummies(df_prepro, columns=cols_to_get_dummies, drop_first=True, dtype=int)

In [36]:
df_prepro.head()

,mergeid,hhid,coupleid,female,age,hhsize,nb_children,chronic_mod,depression_scale,nb_doctor_visits,maxgrip,daily_activities_index,instrumental_activities_index,mobilityind,lgmuscle,grossmotor,finemotor,recall_1,recall_2,bmi,hh_net_income,born_in_itw_country_yes,education_level_1,education_level_2,education_level_3,education_level_4,education_level_5,education_level_6,education_none,education_studying,marital_status_married,marital_status_reg_partnership,marital_status_separated,marital_status_single,marital_status_widowed,partnerinhh_yes,mother_alive_yes,father_alive_yes,help_outside_hh_yes,sphus_fair,sphus_good,sphus_poor,sphus_very_good,hospitalised_last_year_yes,nursing_home_last_year_yes_permanently,nursing_home_last_year_yes_temporarily,smoking_yes,ever_smoked_yes,vigorous_activity_more_than_once_a_week,vigorous_activity_never,vigorous_activity_once_three_times_a_month,job_situation_homemaker,job_situation_other,job_situation_retired,job_situation_unable_to_work,job_situation_unemployed,household_ends_meet_fairly_easily,household_ends_meet_with_great_difficulty,household_ends_meet_with_some_difficulty,has_citizenship_yes,country_BE,country_BG,country_CH,country_CY,country_CZ,country_DE,country_DK,country_EE,country_ES,country_FI,country_FR,country_GR,country_HR,country_HU,country_IE,country_IL,country_IT,country_LT,country_LU,country_LV,country_MT,country_NL,country_PL,country_PT,country_RO,country_SE,country_SI,country_SK
0,AT-000327-01,AT-000327-A,AT-000327-01-02,0,51.900002,2,4,0,0,3,45,0,0,0,0,0,0,5,4,32.787994,28721.849609,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,AT-000327-01,AT-000327-A,AT-000327-01-02,0,54.700001,2,4,1,9,20,37,0,1,2,3,1,0,7,7,20.281233,26432.822266,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,AT-000327-02,AT-000327-A,AT-000327-01-02,1,48.900002,2,4,0,1,2,42,0,0,0,0,0,0,8,7,31.161373,28721.849609,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,AT-000327-02,AT-000327-A,AT-000327-01-02,1,51.700001,2,4,1,3,6,40,0,0,2,0,1,0,8,7,30.461119,26432.822266,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,AT-000674-01,AT-000674-A,,1,63.299999,1,2,2,4,4,26,0,0,0,0,0,0,5,5,27.636055,15720.549805,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [37]:
df_prepro.shape

(281975, 88)

In [38]:
df_prepro.to_csv("../data/easySHARE/easySHARE_preprocessed.csv", index=False)

# Modelling choice summary

- Columns deemed irrelevant:
    * wavepart: irrelevant, 
    * "int_year": irrelevant 
    * "int_month": irrelevant, 
    * "country": used with dummies instead and ISO code,
    * "language": assumed to be mostly contained within country, too many Nans,
    * "dn002_mod"; month of birth, assumed to be contained within age
    * "dn003_mod": year of birth, contained within age, 
    * "birth_country": contained with citizenship 
    * "iv009_mod": location of the interview building, irrelevant,
    * "q34_re": religious denomination, only wave 1
    * "eduyears_mod": years of education, not asked in wave 1 and 3 so removed
    * "int_partner": interview of partner 
    * "sp003-9_X": who gave help, irrelevant,
    * casp": quality of life, lots of NA
    * "euroX": contained in the dependant variable euroD
    * "bfi10_X": too many NA, not relevant as well,
    * "ep0X_mod": only for employed persons, too many NA,
    * "adlwa": use of adla instead,
    * "iadla": use of iadlza instead,
    * "bmi2": use of raw bmi instead,
    * "numeracy_1", "numeracy_2": different questions not asked to the same person
    * "income_pct_wX": use of raw income instead
- Removing columns with more than 10% of missing values
- Indicator variable for missing value if the columns applies to only some persons
- Removing remaining missing values observations
- Normalising one categories for dummies
- Drop wave 3 and 7 as it was a different survey
- Drop variable on respondent history as it was only asked in some waves
- Removing NA for the dependent variable